In [1]:
import pandas as pd
import numpy as np

In [2]:
index = ["bkblk","bknwy","bkon8","bkona","bkspr","bkxbq","bkxcr","bkxwp","blxwp","bxqsq","cntxt","dsopp","dwipd",
 "hdchk","katri","mulch","qxmsq","r2ar8","reskd","reskr","rimmx","rkxwp","rxmsq","simpl","skach","skewr",
 "skrxp","spcop","stlmt","thrsk","wkcti","wkna8","wknck","wkovl","wkpos","wtoeg","win"]

In [3]:
data = pd.read_csv('/home/hamid/hamash_amir/research/rough-set/kr-vs-kp_csv.csv')
data.rename(columns = {'class':"win"}, inplace=True)
data

bkblk bknwy bkon8 bkona bkspr bkxbq bkxcr bkxwp blxwp bxqsq  ... spcop  \
0        f     f     f     f     f     f     f     f     f     f  ...     f   
1        f     f     f     f     t     f     f     f     f     f  ...     f   
2        f     f     f     f     t     f     t     f     f     f  ...     f   
3        f     f     f     f     f     f     f     f     t     f  ...     f   
4        f     f     f     f     f     f     f     f     f     f  ...     f   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
3191     t     f     f     f     f     f     t     f     f     f  ...     f   
3192     t     f     f     f     f     f     t     f     f     f  ...     f   
3193     t     f     f     f     f     f     t     f     f     f  ...     f   
3194     t     f     t     f     f     f     t     f     f     f  ...     f   
3195     t     f     t     f     f     f     t     f     f     f  ...     f   

     stlmt thrsk wkcti wkna8 wknck wkovl wkpos wtoeg    win  
0        f     f     f     f     f     t     t     n    won  
1        f     f     f     f     f     t     t     n    won  
2        f     f     f     f     f     t     t     n    won  
3        f     f     f     f     f     t     t     n    won  
4        f     f     f     f     f     t     t     n    won  
...    ...   ...   ...   ...   ...   ...   ...   ...    ...  
3191     t     f     f     t     f     t     f     n  nowin  
3192     t     f     f     t     f     t     f     n  nowin  
3193     t     f     f     t     f     t     f     n  nowin  
3194     t     f     f     t     f     f     f     n  nowin  
3195     t     f     f     t     f     f     f     n  nowin  

[3196 rows x 37 columns]

In [4]:
# data[data.columns[25]].unique()
u = []
for i in range(0,len(data)):
    u.append(data.loc[i][:].unique().tolist())
m = u[0]
# u[1:]
for k in u[1:]:
    m.extend(k)
print(list(set(m)))

['won', 'f', 'nowin', 'g', 'b', 'w', 't', 'l', 'n']


In [5]:
['f', 'won', 'w', 'b', 'l', 'g', 'nowin', 'n', 't']

['f', 'won', 'w', 'b', 'l', 'g', 'nowin', 'n', 't']

In [6]:
data.columns[:]

Index(['bkblk', 'bknwy', 'bkon8', 'bkona', 'bkspr', 'bkxbq', 'bkxcr', 'bkxwp',
       'blxwp', 'bxqsq', 'cntxt', 'dsopp', 'dwipd', 'hdchk', 'katri', 'mulch',
       'qxmsq', 'r2ar8', 'reskd', 'reskr', 'rimmx', 'rkxwp', 'rxmsq', 'simpl',
       'skach', 'skewr', 'skrxp', 'spcop', 'stlmt', 'thrsk', 'wkcti', 'wkna8',
       'wknck', 'wkovl', 'wkpos', 'wtoeg', 'win'],
      dtype='object')

In [7]:
# data.columns[0]
# for col in data.columns[:-1]:
ns = pd.get_dummies(data[data.columns[:-1]], prefix=data.columns[:-1],drop_first=True, dtype=int)
ns

bkblk_t  bknwy_t  bkon8_t  bkona_t  bkspr_t  bkxbq_t  bkxcr_t  bkxwp_t  \
0           0        0        0        0        0        0        0        0   
1           0        0        0        0        1        0        0        0   
2           0        0        0        0        1        0        1        0   
3           0        0        0        0        0        0        0        0   
4           0        0        0        0        0        0        0        0   
...       ...      ...      ...      ...      ...      ...      ...      ...   
3191        1        0        0        0        0        0        1        0   
3192        1        0        0        0        0        0        1        0   
3193        1        0        0        0        0        0        1        0   
3194        1        0        1        0        0        0        1        0   
3195        1        0        1        0        0        0        1        0   

      blxwp_t  bxqsq_t  ...  skrxp_t  spcop_t  stlmt_t  thrsk_t  wkcti_t  \
0           0        0  ...        0        0        0        0        0   
1           0        0  ...        0        0        0        0        0   
2           0        0  ...        0        0        0        0        0   
3           1        0  ...        0        0        0        0        0   
4           0        0  ...        0        0        0        0        0   
...       ...      ...  ...      ...      ...      ...      ...      ...   
3191        0        0  ...        0        0        1        0        0   
3192        0        0  ...        0        0        1        0        0   
3193        0        0  ...        0        0        1        0        0   
3194        0        0  ...        0        0        1        0        0   
3195        0        0  ...        0        0        1        0        0   

      wkna8_t  wknck_t  wkovl_t  wkpos_t  wtoeg_t  
0           0        0        1        1        0  
1           0        0        1        1        0  
2           0        0        1        1        0  
3           0        0        1        1        0  
4           0        0        1        1        0  
...       ...      ...      ...      ...      ...  
3191        1        0        1        0        0  
3192        1        0        1        0        0  
3193        1        0        1        0        0  
3194        1        0        0        0        0  
3195        1        0        0        0        0  

[3196 rows x 37 columns]

In [8]:
ns.shape[1]

37

In [9]:
ns_y = data['win'].copy()
Y = pd.get_dummies(ns_y,prefix='win',drop_first=True, dtype=int)
Y

win_won
0           1
1           1
2           1
3           1
4           1
...       ...
3191        0
3192        0
3193        0
3194        0
3195        0

[3196 rows x 1 columns]

In [10]:
import sklearn
from sklearn.feature_selection import mutual_info_classif


In [11]:
pheromone = np.ones((ns.shape[1], ns.shape[1]))
# pheromone = np.ones(ns.shape[1])
# pheromone[0][0] = 50
pheromone

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [16]:
traversed_nodes = np.zeros((ns.shape[1],ns.shape[1]))
traversed_nodes

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
def probability_transition_rule(feature1, feature2, pheromone, alpha, beta):
    col_index = ns.columns.tolist()
    i = col_index.index(feature1)
    j = col_index.index(feature2)
    l = col_index.copy()
    
    # l.remove(feature2)
    # mic_ij = mutual_info_classif(X=ns.iloc[:,[i,j]], y=Y['win_won'])
    feat1 = feature1
    feat2 = feature2
    # in formula below : [1] in last stage refer to feat2 mutual info regards to system consist of:
    # feat1 and Y as Target 
    mic_ij = mutual_info_classif(ns[[feat1, feat2]], y=Y['win_won'], random_state=0)[1]
    phrmn_ij = pheromone[i][j]
    init = 0
    for k in range(0,len(l)):
        if k != l.index(feature2):
            phrmn_il = pheromone[i][k]
            mic_il = pheromone[i][k]
            init += (phrmn_il**alpha) * (mic_il**beta)
    pij = ((mic_ij**beta) * (phrmn_ij**alpha)) / init
    return pij


# basic spagetti code is below

In [18]:
# # NUM_1 write stopping criterion
# # NUM_2 write Delta_ij
# # NUM_3 find landa(Fuzzy-Rough-set measure) as classificatiom measure for subsets each Ants found

# ants = 2
features = ns.columns.tolist()
# begin_feature = features.copy()
# alpha = 0.5
# beta = 0.2

# # fg = features.copy()
# ants_route = []
# # for ant in range(0,ants):
# ant_route = []
# #     if ant != 0:
# #         begin_feature.pop(ants_route[ant-1][0])
# fg = begin_feature.copy()
# for feature1 in fg:

#     # if criterion has met:
#     #     break
#     # for first colony generation initialization
#     if len(ant_route) == int(len(ns.columns)/3):
#         break
    
#     print(f'{features.index(feature1)}--{fg.index(feature1)}loop')
#     fg.remove(feature1)
#     feat1_dist_prob = {}
#     i = features.index(feature1)
#     ant_route.append(i)
    
    
#     for feature2 in fg:
#         # if feature1 != feature2:
#         pij = probability_transition_rule(feature1, feature2, pheromone, alpha, beta)
#         # i = features.index(feature1)
#         j = features.index(feature2)
#         feat1_dist_prob[j] = pij
#         # ant_route.append(i)
    
#         print(f'{features.index(feature1)}--{features.index(feature2)}--{pij}')
    
#         # feat1_dist_prob.append(dist_prob)
#     ant_next_target_index = [key for key, value in feat1_dist_prob.items() if value == max(feat1_dist_prob.values())]
#     traversed_nodes[i][j] = 1
#     # mitting criterion
#     ant_route.append(ant_next_target_index)
#     print(ant_route)
# ants_route.append(ant_route)


In [69]:
# mic1 = mutual_info_classif(ns[[features[0], features[1]]], y=Y['win_won'],random_state=0)
# mic2 = mutual_info_classif(ns[[features[0]]], y=Y['win_won'],random_state=0)
# print(mic1)
# print(mic2)

[0.00025006 0.00254544]
[0.00223727]


In [1]:
# global traversed_nodes,pheromone
# pheromone = np.ones((ns.shape[1], ns.shape[1]))
# traversed_nodes = np.zeros((ns.shape[1],ns.shape[1]))

def next_ant_target(ant_route, feature1, feature_choices, pheromone, dataframe, traversed_nodes):
    alpha = 0.5
    beta = 0.5
    # traversed_nodes = np.zeros((ns.shape[1],ns.shape[1]))
    # if ant_route.empty() == False:
    #     ant_route = []
    features = dataframe.columns.tolist()
    fg = feature_choices.copy()
    fg.remove(feature1)
    i = features.index(feature1)
    ant_route.append(i)
    print(f'antroute1 -- {ant_route}')

    ### below line cause loop doesnt choose from chosen features and nodes 
    ### we remove ant_route frome fg 
    anty = ant_route.copy()
    if i in anty and anty[0] != i:
        anty.remove(i)
        print(f'antroute2 -- {anty}')
        for x in anty:
            fg.remove(features[x])
    ###

    
    
    # ant_route = []
    # ant_route.append(i)
    feat1_dist_prob = {}
    for feature2 in fg:
        # if feature1 != feature2:
        pij = probability_transition_rule(feature1, feature2, pheromone, alpha, beta)
        # i = features.index(feature1)
        j = features.index(feature2)
        feat1_dist_prob[j] = pij
        # ant_route.append(i)
    
        print(f'{features.index(feature1)}' + f'--{features.index(feature2)}--' + f'{pij}')
    
        # feat1_dist_prob.append(dist_prob)
    ant_next_target_index = [key for key, value in feat1_dist_prob.items() if value == max(feat1_dist_prob.values())][0]
    traversed_nodes[i][j] = 1
    # mitting criterion
    ant_route.append(ant_next_target_index)
    fg_index = [key for key,value in feat1_dist_prob.items()]
    return ant_route, fg, traversed_nodes,fg_index,feat1_dist_prob,pheromone

In [60]:
a = [99,22]
a[-1]

22

In [ ]:
ant_route = []
feature_s = ns.columns.tolist()
feature1 = feature_s[0]
feature_choices = features
pheromone = np.ones((ns.shape[1], ns.shape[1]))
traversed_nodes = np.zeros((ns.shape[1],ns.shape[1]))

while len(ant_route) < 10:
    ant_route, _, traversed_nodes, _, _, pheromone = next_ant_target(ant_route, feature1, feature_choices, pheromone, ns, traversed_nodes)
    print(f'antroute3 -- {ant_route}')
    feature1_index = ant_route[-1]
    feature1 = feature_s[feature1_index]
print(f'antroute4 -- {ant_route}')

In [ ]:
# mutual information differ every time we run it !!
features = ns.columns.tolist()
ant_route, fg, traversed_nodes,fg_index,feat1_dist_prob,pheromone = next_ant_target(features[0], features, pheromone, ns, traversed_nodes=traversed_nodes)
# ant_rout[-1] = feature1
# fg = features
# traversed_nodes = traversed_nodes
# pheromone = pheromone
print('pheromone' + f'{pheromone}')
print('ant_route' + f'{ant_route}')
print('fg' + f'{fg}')
print('traversed_nodes' + f'{traversed_nodes}')
print('fg_index' + f'{fg_index}')
print('feat1_dist_prob' + f'{feat1_dist_prob}')

In [109]:
features = ns.columns.tolist()
features

['bkblk_t',
 'bknwy_t',
 'bkon8_t',
 'bkona_t',
 'bkspr_t',
 'bkxbq_t',
 'bkxcr_t',
 'bkxwp_t',
 'blxwp_t',
 'bxqsq_t',
 'cntxt_t',
 'dsopp_t',
 'dwipd_l',
 'hdchk_t',
 'katri_n',
 'katri_w',
 'mulch_t',
 'qxmsq_t',
 'r2ar8_t',
 'reskd_t',
 'reskr_t',
 'rimmx_t',
 'rkxwp_t',
 'rxmsq_t',
 'simpl_t',
 'skach_t',
 'skewr_t',
 'skrxp_t',
 'spcop_t',
 'stlmt_t',
 'thrsk_t',
 'wkcti_t',
 'wkna8_t',
 'wknck_t',
 'wkovl_t',
 'wkpos_t',
 'wtoeg_t']

In [118]:
pheromone = np.ones((ns.shape[1], ns.shape[1]))
traversed_nodes = np.zeros((ns.shape[1],ns.shape[1]))
base_features = ns.columns.tolist()
features = ns.columns.tolist()
feature1 = features[0]
ant_routes = []
while len(ant_route) < 10:
    ant_choice, fg, traversed_nodes_init,fg_index,feat1_dist_prob,pheromone_init = next_ant_target(feature1, features, pheromone, ns, traversed_nodes)
    feature1 = base_features[ant_choice[-1]]
    ant_routes.append(ant_choice[0])
    # features = fg
    # traversed_nodes = traversed_nodes_init
    # pheromone = pheromone_init
    # ant_route = ant_route_init
print('pheromone' + f'{pheromone}')
print('ant_route' + f'{ant_routes}')
print('fg' + f'{fg}')
print('traversed_nodes' + f'{traversed_nodes}')
print('fg_index' + f'{fg_index}')
print('feat1_dist_prob' + f'{feat1_dist_prob}')

pheromone[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
ant_route[]
fg['bknwy_t', 'bkon8_t', 'bkona_t', 'bkspr_t', 'bkxbq_t', 'bkxcr_t', 'bkxwp_t', 'blxwp_t', 'bxqsq_t', 'cntxt_t', 'dsopp_t', 'dwipd_l', 'hdchk_t', 'katri_n', 'katri_w', 'mulch_t', 'qxmsq_t', 'r2ar8_t', 'reskd_t', 'reskr_t', 'rimmx_t', 'rkxwp_t', 'rxmsq_t', 'simpl_t', 'skach_t', 'skewr_t', 'skrxp_t', 'spcop_t', 'stlmt_t', 'thrsk_t', 'wkcti_t', 'wkna8_t', 'wknck_t', 'wkovl_t', 'wkpos_t', 'wtoeg_t']
traversed_nodes[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
fg_index[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
feat1_dist_prob{1: 0.001401455262310136, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0005506991428479221, 6: 0.0022439832552

In [52]:
features = ns.columns.tolist()
alpha = 0.5
beta = 0.5
pijk = probability_transition_rule(features[0], features[3], pheromone, alpha, beta)
pijk

0.00043925640287619693

An ANT COLONY from Bing Chat GPT

In [1]:
import numpy as np
import pandas as pd

def ant_colony_algorithm(feature_matrix, landa):
    # initialize pheromone matrix
    pheromone = np.ones(feature_matrix.shape[1])
    # initialize ant colony
    ants = np.zeros((feature_matrix.shape[0], feature_matrix.shape[1]))
    # initialize best feature subset
    best_subset = []
    # initialize best score
    best_score = 0
    
    # iterate until stopping criterion is met
    while True:
        # iterate over each ant
        for i in range(ants.shape[0]):
            # calculate probability of selecting each feature
            probability = pheromone / np.sum(pheromone)
            # select features based on probability
            selected_features = np.random.choice(feature_matrix.shape[1], size=10000, replace=False, p=probability)
            # add selected features to ant colony
            ants[i, selected_features] = 1
        
        # calculate score for each feature subset
        scores = np.sum(ants * feature_matrix, axis=1) / np.sum(feature_matrix, axis=1)
        # find best feature subset and score
        best_subset = ants[np.argmax(scores)]
        best_score = np.max(scores)
        
        # update pheromone matrix based on best feature subset
        pheromone *= (1 - landa)
        pheromone += landa * best_subset
        
        # check stopping criterion
        if best_score >= landa:
            break
    
    return best_subset

# example usage
feature_matrix = pd.DataFrame(np.random.rand(1000, 10000))
landa = 0.5

best_subset = ant_colony_algorithm(feature_matrix, landa)

print(best_subset)

[1. 1. 1. ... 1. 1. 1.]


In [97]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.feature_selection import mutual_info_classif
from pathlib import Path
import sys,os
import importlib
from frlearn.classifiers import FRNN


index = ["bkblk","bknwy","bkon8","bkona","bkspr","bkxbq","bkxcr","bkxwp","blxwp","bxqsq","cntxt","dsopp","dwipd",
 "hdchk","katri","mulch","qxmsq","r2ar8","reskd","reskr","rimmx","rkxwp","rxmsq","simpl","skach","skewr",
 "skrxp","spcop","stlmt","thrsk","wkcti","wkna8","wknck","wkovl","wkpos","wtoeg","win"]


data = pd.read_csv('/home/hamid/hamash_amir/research/rough_set_cloned/kr-vs-kp_csv.csv')
data.rename(columns = {'class':"win"}, inplace=True)

ns = pd.get_dummies(data[data.columns[:-1]], prefix=data.columns[:-1],drop_first=True, dtype=int)

ns_y = data['win'].copy()
Y = pd.get_dummies(ns_y,prefix='win',drop_first=True, dtype=int)


class Colony:
    


    dataframe: object = ns
    pheromone = np.ones((ns.shape[1], ns.shape[1]))
    traversed_nodes = np.zeros((ns.shape[1],ns.shape[1]))
    ant_route: list[int] = []
    alpha: int = 0
    beta: int = 0
    feature_choices: list[str] = dataframe.columns.tolist()
    feature1: str
    log: list[str] = []
    fg: list[str] = feature_choices.copy()

    overall_ant_route: dict = {}
    
    # def __init__(self):
    #     self.ant_route = ant_route
    #     self.feature1 = feature1
    #     self.fg = fg
        
    @classmethod
    def add_generation(cls):
        cls.colony_number += 1

    
    @classmethod
    def get_log(cls):
        print(cls.log)
    
    @classmethod
    def reset_colony(cls):
        
        Colony.pheromone = np.ones((ns.shape[1], ns.shape[1]))
        Colony.traversed_nodes = np.zeros((ns.shape[1], ns.shape[1]))

        Colony.overall_ant_route.clear()
        Colony.log = []
        Colony.fg = cls.feature_choices.copy()
        
    @classmethod
    def initialization_alpha_beta(cls, alpha, beta):
        
        cls.alpha = alpha
        cls.beta = beta

    @classmethod
    def reset_ant_route(cls):
        cls.ant_route = []

    @classmethod
    def initialize_feature1(cls):
        ant_route = cls.ant_route
        if not ant_route:
            cls.feature1 = np.random.choice(cls.feature_choices)
        else:
            cls.feature1 = cls.feature_choices[cls.ant_route[-1]]
    
    
    @classmethod
    def ant(cls):

        cls.initialization_alpha_beta(0.5, 0.5)
        cls.initialize_feature1()
        feature1 = cls.feature1
        features = cls.dataframe.columns.tolist()
        if any(feature1 in x for x in cls.fg):
            cls.fg.remove(feature1)
        i = features.index(feature1)
        if i not in cls.ant_route:
            cls.ant_route.append(i)

        feat1_dist_prob = {}
        for feature2 in cls.fg:
           
            pij = cls.__probability_transition_rule(cls.feature1, feature2)
      
            j = features.index(feature2)
            feat1_dist_prob[j] = pij

        
            cls.log.append(f'{features.index(cls.feature1)}' 
                           f'--{features.index(feature2)}--{float(pij)}')

    
        ant_next_target_index = [key for key, value in feat1_dist_prob.items()\
            if value == max(feat1_dist_prob.values())][0]
        cls.traversed_nodes[i,ant_next_target_index] = 1
        # mitting criterion
        cls.ant_route.append(ant_next_target_index)
        fg_index = [key for key,value in feat1_dist_prob.items()]

    
    @classmethod
    def ants(
        cls, make_initialize: bool | None=None,
        number_of_ants_first_gen: int | None=None,
        number_of_ants_next_gen: int | None=None, 
        criteria: int | str | None=None):
        
        if cls.colony_number == 0 or make_initialize == True:
            cls.initialize_colony(
                number_of_ants_first_generation=number_of_ants_first_gen,
                                init_criteria=criteria)
        cls.generate_next_ants(
            number_of_ants_next_generation=number_of_ants_next_gen)
    @classmethod
    def change_pheromone(cls):
        """
        After each generation of several ants or after each generation 
        it update pheromone matrix according to following formula:
         
        phromone[i,j](t+1) = (1-rho)*phromone[i,j](t) + Delta(ij)(t)
        
        Delta(ij)(t) = |_| = Delta(ij)(t) = 
                       |_|   sigma(landa_prime(ant_route)/len(ant_route)) ,if traversed_node[i,j] = 1
                       |_| = 0                                            ,if traversed_node[i,j] = 0
        
        landa_prime is rough_set_measure           
        """
        X = cls.dataframe.iloc[:,cls.ant_route]
        ns_y = cls.dataframe['win'].copy()
        y = pd.get_dummies(ns_y,prefix='win',drop_first=True, dtype=int)
        
        
        clf = FRNN(upper_weights=None, lower_weights=None, upper_k=1, lower_k=1)
        model = clf(X, y)

    @classmethod
    def positive_region(cls):
        # assuming df is your DataFrame
        # assuming the last column is the decision column
        # partition dataframe based on decision classes
        df = cls.dataframe
        partitions = [group for _, group in df.groupby(df.iloc[:,-1])]
    
        # find positive region for each partition
        positive_regions = [group[group.duplicated(df.columns[:-1], keep=False)] for group in partitions]
    
        # return union of all positive regions
        return pd.concat(positive_regions)


    
    @classmethod
    def __probability_transition_rule(cls, feature1, feature2):
        col_index = ns.columns.tolist()
        i = col_index.index(feature1)
        j = col_index.index(feature2)
        l = col_index.copy()
        

        feat1 = feature1
        feat2 = feature2

        mic_ij = mutual_info_classif(ns[[feat1, feat2]], y=Y['win_won'], random_state=0)[1]
        phrmn_ij = cls.pheromone[i,j]
        init = 0
        for k in range(0,len(l)):
            if k != l.index(feature2):
                phrmn_il = cls.pheromone[i,k]
                mic_il = cls.pheromone[i,k]
                init += (phrmn_il**cls.alpha) * (mic_il**cls.beta)
        pij = ((mic_ij**cls.beta) * (phrmn_ij**cls.alpha)) / init
        return pij

    @classmethod 
    def initialize_colony(cls, number_of_ants_first_generation, init_criteria):
        """
        first of all we run this method for initialize first generation of colony
        in this method we set manually number_of_ants_first_generation variable
        to a number As a CRITERIA just for initialize pheromone matrix.in next 
        generations we set rough set feature selection CRITERIA and when 
        selected features by each ant in a colony met this limit that ant stop
        exploration and next ant begins.
        CAUTIONS!: RUN THIS METHOD JUST ONE TIME IN EACH COLONY!
        """ 
        
        # cls.overal_ant_route = {}
        j = 0
        while j < number_of_ants_first_generation:
            i = 0
            while i < init_criteria-1: 
                cls.ant()
                i += 1
            cls.overall_ant_route[j] = cls.ant_route
            cls.reset_ant_route()
            j += 1


    @classmethod
    def is_rough_set_criteria_met(cls, selected_feature: list[int]) -> bool:
        pass
        
    @classmethod 
    def generate_next_ants(cls, number_of_ants_next_generation: int):
        
        try:
            if cls.colony_number > 0:
                j = 0
                while j < number_of_ants_next_generation:
                    while not cls.is_rough_set_criteria_met(cls.ant_route): 
                    # for j in range(number_of_ants_first_generation):
                        cls.ant()
                        i += 1
                    j += 1
                    cls.reset_ant_route()

            else:
                error = Exception("Colony generation doesnt initialized first!")
                raise error
        except:
            print(error)


In [15]:
Colony.reset_colony()

In [42]:
Colony.overall_ant_route

{}

In [39]:
Colony.initialize_colony(2, 2)

In [24]:
Colony.overall_ant_route 

{0: [32, 21, 9], 1: [19, 9, 33]}

In [14]:
Colony.initialize_colony(2, 3)

In [15]:
Colony.overall_ant_route

{0: [9, 7, 15], 1: [5, 15, 36]}

In [8]:
Colony.get_log()

['31--0--0.0', '31--1--0.001401455262310136', '31--2--0.0', '31--3--0.0', '31--4--0.0', '31--5--0.0006572908954166817', '31--6--0.0022439832552795247', '31--7--0.004016667769287638', '31--8--0.0', '31--9--0.00710357754890756', '31--10--0.0', '31--11--0.0', '31--12--0.0', '31--13--0.0', '31--14--0.0019918557764496293', '31--15--0.003970892173563391', '31--16--0.0024176981408798523', '31--17--0.0', '31--18--0.0023599131064591296', '31--19--0.0', '31--20--0.0', '31--21--0.010176304809302022', '31--22--0.0009847219318264294', '31--23--0.002131013006868446', '31--24--0.0', '31--25--0.0', '31--26--0.0', '31--27--0.001084775290018463', '31--28--0.0', '31--29--0.0028109388829424603', '31--30--0.0', '31--32--0.004208224063542534', '31--33--0.007101379414559333', '31--34--0.0', '31--35--0.0014632796494194094', '31--36--0.0031941196673904277', '21--0--0.0', '21--1--0.001401455262310136', '21--2--0.0', '21--3--0.0', '21--4--0.0', '21--5--0.0006572908954166817', '21--6--0.0022439832552795247', '21-

In [39]:
importlib.import_module('Moduls.Colony')

<module 'Moduls.Colony' from '/home/hamid/hamash_amir/research/rough_set_cloned/Moduls/Colony.py'>

In [17]:
yy = pd.get_dummies(data['win'],prefix='win',drop_first=True, dtype=int)
yy

win_won
0           1
1           1
2           1
3           1
4           1
...       ...
3191        0
3192        0
3193        0
3194        0
3195        0

[3196 rows x 1 columns]

In [18]:
df = pd.concat([ns,yy], axis=1)
df

bkblk_t  bknwy_t  bkon8_t  bkona_t  bkspr_t  bkxbq_t  bkxcr_t  bkxwp_t  \
0           0        0        0        0        0        0        0        0   
1           0        0        0        0        1        0        0        0   
2           0        0        0        0        1        0        1        0   
3           0        0        0        0        0        0        0        0   
4           0        0        0        0        0        0        0        0   
...       ...      ...      ...      ...      ...      ...      ...      ...   
3191        1        0        0        0        0        0        1        0   
3192        1        0        0        0        0        0        1        0   
3193        1        0        0        0        0        0        1        0   
3194        1        0        1        0        0        0        1        0   
3195        1        0        1        0        0        0        1        0   

      blxwp_t  bxqsq_t  ...  spcop_t  stlmt_t  thrsk_t  wkcti_t  wkna8_t  \
0           0        0  ...        0        0        0        0        0   
1           0        0  ...        0        0        0        0        0   
2           0        0  ...        0        0        0        0        0   
3           1        0  ...        0        0        0        0        0   
4           0        0  ...        0        0        0        0        0   
...       ...      ...  ...      ...      ...      ...      ...      ...   
3191        0        0  ...        0        1        0        0        1   
3192        0        0  ...        0        1        0        0        1   
3193        0        0  ...        0        1        0        0        1   
3194        0        0  ...        0        1        0        0        1   
3195        0        0  ...        0        1        0        0        1   

      wknck_t  wkovl_t  wkpos_t  wtoeg_t  win_won  
0           0        1        1        0        1  
1           0        1        1        0        1  
2           0        1        1        0        1  
3           0        1        1        0        1  
4           0        1        1        0        1  
...       ...      ...      ...      ...      ...  
3191        0        1        0        0        0  
3192        0        1        0        0        0  
3193        0        1        0        0        0  
3194        0        0        0        0        0  
3195        0        0        0        0        0  

[3196 rows x 38 columns]

In [161]:
partitions = [group for _, group in df.groupby(df.iloc[:,-1])]
positive_regions = [group[group.duplicated(df.columns[:-1], keep=False)] for group in partitions]
print(positive_regions)

[Empty DataFrame
Columns: [bkblk_t, bknwy_t, bkon8_t, bkona_t, bkspr_t, bkxbq_t, bkxcr_t, bkxwp_t, blxwp_t, bxqsq_t, cntxt_t, dsopp_t, dwipd_l, hdchk_t, katri_n, katri_w, mulch_t, qxmsq_t, r2ar8_t, reskd_t, reskr_t, rimmx_t, rkxwp_t, rxmsq_t, simpl_t, skach_t, skewr_t, skrxp_t, spcop_t, stlmt_t, thrsk_t, wkcti_t, wkna8_t, wknck_t, wkovl_t, wkpos_t, wtoeg_t, win_won]
Index: []

[0 rows x 38 columns], Empty DataFrame
Columns: [bkblk_t, bknwy_t, bkon8_t, bkona_t, bkspr_t, bkxbq_t, bkxcr_t, bkxwp_t, blxwp_t, bxqsq_t, cntxt_t, dsopp_t, dwipd_l, hdchk_t, katri_n, katri_w, mulch_t, qxmsq_t, r2ar8_t, reskd_t, reskr_t, rimmx_t, rkxwp_t, rxmsq_t, simpl_t, skach_t, skewr_t, skrxp_t, spcop_t, stlmt_t, thrsk_t, wkcti_t, wkna8_t, wknck_t, wkovl_t, wkpos_t, wtoeg_t, win_won]
Index: []

[0 rows x 38 columns]]


In [ ]:
t1 = partitions[1].iloc[0:1,:-1]
t2 = partitions[1].iloc[1:2,:-1]
def equal_elements(t1, t2):
    return [x for x, y in zip(t1, t2) if list(x) == list(y)]
r = equal_elements(t1, t2)
r

In [106]:
Y

win_won
0           1
1           1
2           1
3           1
4           1
...       ...
3191        0
3192        0
3193        0
3194        0
3195        0

[3196 rows x 1 columns]

In [131]:
if partitions[1].iloc[[1],[0]].values == partitions[0].iloc[[0],[0]].values:
    print('yes')

yes


In [160]:
# partition 0
col = {}
# for j in range(len(ns.columns)):
row = []
for i in range(len(partitions[0])):
    for k in range(len(partitions[1])):  
        number_of_differences = np.count_nonzero(np.subtract(partitions[0].iloc[[i],:].values, partitions[1].iloc[[k],:].values))

        print(f'column{i}--part0{j}--part1{number_of_differences}')    
col[f'col{j}'] = row
col 
# ns.iloc[[2],[1]]

KeyError: 0

In [168]:
arr = partitions[0].iloc[[1],:].values
np.count_nonzero(arr)

9

In [169]:
diff = np.subtract(partitions[0].iloc[[1],:].values, partitions[1].iloc[[1],:].values)
np.count_nonzero(diff)

3

In [156]:
partitions[partitions == 1].fillna(0)

bkblk_t  bknwy_t  bkon8_t  bkona_t  bkspr_t  bkxbq_t  bkxcr_t  bkxwp_t  \
1        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
905      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

     blxwp_t  bxqsq_t  ...  spcop_t  stlmt_t  thrsk_t  wkcti_t  wkna8_t  \
1        0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
905      0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   

     wknck_t  wkovl_t  wkpos_t  wtoeg_t  win_won  
1        0.0      0.0      0.0      0.0      0.0  
905      0.0      0.0      0.0      0.0      0.0  

[2 rows x 38 columns]

In [17]:
list(t2.iloc[:,4])

[1]

In [18]:
list(t1.iloc[:,4])

[0]

In [39]:
empty = []
for i,j in zip(list(t1.iterrows()),list(t2.iterrows())):
    # print(f'i{list(i)}--j{list(j)}')
    print(list(i))
    # if i != j:
    #     empty.append(1)


[0, bkblk_t    0
bknwy_t    0
bkon8_t    0
bkona_t    0
bkspr_t    0
bkxbq_t    0
bkxcr_t    0
bkxwp_t    0
blxwp_t    0
bxqsq_t    0
cntxt_t    0
dsopp_t    0
dwipd_l    1
hdchk_t    0
katri_n    1
katri_w    0
mulch_t    0
qxmsq_t    0
r2ar8_t    1
reskd_t    0
reskr_t    0
rimmx_t    0
rkxwp_t    0
rxmsq_t    0
simpl_t    0
skach_t    0
skewr_t    1
skrxp_t    0
spcop_t    0
stlmt_t    0
thrsk_t    0
wkcti_t    0
wkna8_t    0
wknck_t    0
wkovl_t    1
wkpos_t    1
wtoeg_t    0
Name: 0, dtype: int64]


In [43]:
for x,y in t1.iterrows():
    print(y)

bkblk_t    0
bknwy_t    0
bkon8_t    0
bkona_t    0
bkspr_t    0
bkxbq_t    0
bkxcr_t    0
bkxwp_t    0
blxwp_t    0
bxqsq_t    0
cntxt_t    0
dsopp_t    0
dwipd_l    1
hdchk_t    0
katri_n    1
katri_w    0
mulch_t    0
qxmsq_t    0
r2ar8_t    1
reskd_t    0
reskr_t    0
rimmx_t    0
rkxwp_t    0
rxmsq_t    0
simpl_t    0
skach_t    0
skewr_t    1
skrxp_t    0
spcop_t    0
stlmt_t    0
thrsk_t    0
wkcti_t    0
wkna8_t    0
wknck_t    0
wkovl_t    1
wkpos_t    1
wtoeg_t    0
Name: 0, dtype: int64
