In [1]:
import pandas as pd
import numpy as np

In [2]:
index = ["bkblk","bknwy","bkon8","bkona","bkspr","bkxbq","bkxcr","bkxwp","blxwp","bxqsq","cntxt","dsopp","dwipd",
 "hdchk","katri","mulch","qxmsq","r2ar8","reskd","reskr","rimmx","rkxwp","rxmsq","simpl","skach","skewr",
 "skrxp","spcop","stlmt","thrsk","wkcti","wkna8","wknck","wkovl","wkpos","wtoeg","win"]

In [3]:
data = pd.read_csv('C:/Users/sama/Downloads/kr-vs-kp - Copy.csv',names=index)
data

bkblk bknwy bkon8 bkona bkspr bkxbq bkxcr bkxwp blxwp bxqsq  ... spcop  \
0        f     f     f     f     f     f     f     f     f     f  ...     f   
1        f     f     f     f     t     f     f     f     f     f  ...     f   
2        f     f     f     f     t     f     t     f     f     f  ...     f   
3        f     f     f     f     f     f     f     f     t     f  ...     f   
4        f     f     f     f     f     f     f     f     f     f  ...     f   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
3191     t     f     f     f     f     f     t     f     f     f  ...     f   
3192     t     f     f     f     f     f     t     f     f     f  ...     f   
3193     t     f     f     f     f     f     t     f     f     f  ...     f   
3194     t     f     t     f     f     f     t     f     f     f  ...     f   
3195     t     f     t     f     f     f     t     f     f     f  ...     f   

     stlmt thrsk wkcti wkna8 wknck wkovl wkpos wtoeg    win  
0        f     f     f     f     f     t     t     n    won  
1        f     f     f     f     f     t     t     n    won  
2        f     f     f     f     f     t     t     n    won  
3        f     f     f     f     f     t     t     n    won  
4        f     f     f     f     f     t     t     n    won  
...    ...   ...   ...   ...   ...   ...   ...   ...    ...  
3191     t     f     f     t     f     t     f     n  nowin  
3192     t     f     f     t     f     t     f     n  nowin  
3193     t     f     f     t     f     t     f     n  nowin  
3194     t     f     f     t     f     f     f     n  nowin  
3195     t     f     f     t     f     f     f     n  nowin  

[3196 rows x 37 columns]

In [4]:
# data[data.columns[25]].unique()
u = []
for i in range(0,len(data)):
    u.append(data.loc[i][:].unique().tolist())
m = u[0]
# u[1:]
for k in u[1:]:
    m.extend(k)
print(list(set(m)))

['f', 'won', 'w', 'b', 'l', 'g', 'nowin', 'n', 't']


In [5]:
data

bkblk bknwy bkon8 bkona bkspr bkxbq bkxcr bkxwp blxwp bxqsq  ... spcop  \
0        f     f     f     f     f     f     f     f     f     f  ...     f   
1        f     f     f     f     t     f     f     f     f     f  ...     f   
2        f     f     f     f     t     f     t     f     f     f  ...     f   
3        f     f     f     f     f     f     f     f     t     f  ...     f   
4        f     f     f     f     f     f     f     f     f     f  ...     f   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
3191     t     f     f     f     f     f     t     f     f     f  ...     f   
3192     t     f     f     f     f     f     t     f     f     f  ...     f   
3193     t     f     f     f     f     f     t     f     f     f  ...     f   
3194     t     f     t     f     f     f     t     f     f     f  ...     f   
3195     t     f     t     f     f     f     t     f     f     f  ...     f   

     stlmt thrsk wkcti wkna8 wknck wkovl wkpos wtoeg    win  
0        f     f     f     f     f     t     t     n    won  
1        f     f     f     f     f     t     t     n    won  
2        f     f     f     f     f     t     t     n    won  
3        f     f     f     f     f     t     t     n    won  
4        f     f     f     f     f     t     t     n    won  
...    ...   ...   ...   ...   ...   ...   ...   ...    ...  
3191     t     f     f     t     f     t     f     n  nowin  
3192     t     f     f     t     f     t     f     n  nowin  
3193     t     f     f     t     f     t     f     n  nowin  
3194     t     f     f     t     f     f     f     n  nowin  
3195     t     f     f     t     f     f     f     n  nowin  

[3196 rows x 37 columns]

In [6]:
data.columns[:-1]

Index(['bkblk', 'bknwy', 'bkon8', 'bkona', 'bkspr', 'bkxbq', 'bkxcr', 'bkxwp',
       'blxwp', 'bxqsq', 'cntxt', 'dsopp', 'dwipd', 'hdchk', 'katri', 'mulch',
       'qxmsq', 'r2ar8', 'reskd', 'reskr', 'rimmx', 'rkxwp', 'rxmsq', 'simpl',
       'skach', 'skewr', 'skrxp', 'spcop', 'stlmt', 'thrsk', 'wkcti', 'wkna8',
       'wknck', 'wkovl', 'wkpos', 'wtoeg'],
      dtype='object')

In [7]:
# data.columns[0]
# for col in data.columns[:-1]:
ns = pd.get_dummies(data[data.columns[:-1]], prefix=data.columns[:-1],drop_first=True)
ns

bkblk_t  bknwy_t  bkon8_t  bkona_t  bkspr_t  bkxbq_t  bkxcr_t  bkxwp_t  \
0           0        0        0        0        0        0        0        0   
1           0        0        0        0        1        0        0        0   
2           0        0        0        0        1        0        1        0   
3           0        0        0        0        0        0        0        0   
4           0        0        0        0        0        0        0        0   
...       ...      ...      ...      ...      ...      ...      ...      ...   
3191        1        0        0        0        0        0        1        0   
3192        1        0        0        0        0        0        1        0   
3193        1        0        0        0        0        0        1        0   
3194        1        0        1        0        0        0        1        0   
3195        1        0        1        0        0        0        1        0   

      blxwp_t  bxqsq_t  ...  skrxp_t  spcop_t  stlmt_t  thrsk_t  wkcti_t  \
0           0        0  ...        0        0        0        0        0   
1           0        0  ...        0        0        0        0        0   
2           0        0  ...        0        0        0        0        0   
3           1        0  ...        0        0        0        0        0   
4           0        0  ...        0        0        0        0        0   
...       ...      ...  ...      ...      ...      ...      ...      ...   
3191        0        0  ...        0        0        1        0        0   
3192        0        0  ...        0        0        1        0        0   
3193        0        0  ...        0        0        1        0        0   
3194        0        0  ...        0        0        1        0        0   
3195        0        0  ...        0        0        1        0        0   

      wkna8_t  wknck_t  wkovl_t  wkpos_t  wtoeg_t  
0           0        0        1        1        0  
1           0        0        1        1        0  
2           0        0        1        1        0  
3           0        0        1        1        0  
4           0        0        1        1        0  
...       ...      ...      ...      ...      ...  
3191        1        0        1        0        0  
3192        1        0        1        0        0  
3193        1        0        1        0        0  
3194        1        0        0        0        0  
3195        1        0        0        0        0  

[3196 rows x 37 columns]

In [8]:
ns.shape[1]

37

In [9]:
ns_y = data['win'].copy()
Y = pd.get_dummies(ns_y,prefix='win',drop_first=True)
Y

win_won
0           1
1           1
2           1
3           1
4           1
...       ...
3191        0
3192        0
3193        0
3194        0
3195        0

[3196 rows x 1 columns]

In [10]:
from sklearn.feature_selection import mutual_info_classif


In [11]:
pheromone = np.ones((ns.shape[1], ns.shape[1]))
# pheromone = np.ones(ns.shape[1])
# pheromone[0][0] = 50
pheromone

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [12]:
traversed_nodes = np.zeros((ns.shape[1],ns.shape[1]))
traversed_nodes

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
def probability_transition_rule(feature1, feature2, pheromone, alpha, beta):
    col_index = ns.columns.tolist()
    i = col_index.index(feature1)
    j = col_index.index(feature2)
    l = col_index.copy()
    
    # l.remove(feature2)
    # mic_ij = mutual_info_classif(X=ns.iloc[:,[i,j]], y=Y['win_won'])
    feat1 = feature1
    feat2 = feature2
    # in formula below : [1] in last stage refer to feat2 mutual info regards to system consist of:
    # feat1 and Y as Target 
    mic_ij = mutual_info_classif(ns[[feat1, feat2]], y=Y['win_won'], random_state=0)[1]
    phrmn_ij = pheromone[i][j]
    init = 0
    for k in range(0,len(l)):
        if k != l.index(feature2):
            phrmn_il = pheromone[i][k]
            mic_il = pheromone[i][k]
            init += (phrmn_il**alpha) * (mic_il**beta)
    pij = ((mic_ij**beta) * (phrmn_ij**alpha)) / init
    return pij


# basic spagetti code is below

In [18]:
# # NUM_1 write stopping criterion
# # NUM_2 write Delta_ij
# # NUM_3 find landa(Fuzzy-Rough-set measure) as classificatiom measure for subsets each Ants found

# ants = 2
features = ns.columns.tolist()
# begin_feature = features.copy()
# alpha = 0.5
# beta = 0.2

# # fg = features.copy()
# ants_route = []
# # for ant in range(0,ants):
# ant_route = []
# #     if ant != 0:
# #         begin_feature.pop(ants_route[ant-1][0])
# fg = begin_feature.copy()
# for feature1 in fg:

#     # if criterion has met:
#     #     break
#     # for first colony generation initialization
#     if len(ant_route) == int(len(ns.columns)/3):
#         break
    
#     print(f'{features.index(feature1)}--{fg.index(feature1)}loop')
#     fg.remove(feature1)
#     feat1_dist_prob = {}
#     i = features.index(feature1)
#     ant_route.append(i)
    
    
#     for feature2 in fg:
#         # if feature1 != feature2:
#         pij = probability_transition_rule(feature1, feature2, pheromone, alpha, beta)
#         # i = features.index(feature1)
#         j = features.index(feature2)
#         feat1_dist_prob[j] = pij
#         # ant_route.append(i)
    
#         print(f'{features.index(feature1)}--{features.index(feature2)}--{pij}')
    
#         # feat1_dist_prob.append(dist_prob)
#     ant_next_target_index = [key for key, value in feat1_dist_prob.items() if value == max(feat1_dist_prob.values())]
#     traversed_nodes[i][j] = 1
#     # mitting criterion
#     ant_route.append(ant_next_target_index)
#     print(ant_route)
# ants_route.append(ant_route)


In [69]:
# mic1 = mutual_info_classif(ns[[features[0], features[1]]], y=Y['win_won'],random_state=0)
# mic2 = mutual_info_classif(ns[[features[0]]], y=Y['win_won'],random_state=0)
# print(mic1)
# print(mic2)

[0.00025006 0.00254544]
[0.00223727]


In [59]:
# global traversed_nodes,pheromone
# pheromone = np.ones((ns.shape[1], ns.shape[1]))
# traversed_nodes = np.zeros((ns.shape[1],ns.shape[1]))

def next_ant_target(ant_route, feature1, feature_choices, pheromone, dataframe, traversed_nodes):
    alpha = 0.5
    beta = 0.5
    # traversed_nodes = np.zeros((ns.shape[1],ns.shape[1]))
    # if ant_route.empty() == False:
    #     ant_route = []
    features = dataframe.columns.tolist()
    fg = feature_choices.copy()
    fg.remove(feature1)
    i = features.index(feature1)
    ant_route.append(i)
    print(f'antroute1 -- {ant_route}')

    ### below line cause loop doesnt choose from chosen features and nodes 
    ### we remove ant_route frome fg 
    anty = ant_route.copy()
    if i in anty and anty[0] != i:
        anty.remove(i)
        print(f'antroute2 -- {anty}')
        for x in anty:
            fg.remove(features[x])
    ###

    
    
    # ant_route = []
    # ant_route.append(i)
    feat1_dist_prob = {}
    for feature2 in fg:
        # if feature1 != feature2:
        pij = probability_transition_rule(feature1, feature2, pheromone, alpha, beta)
        # i = features.index(feature1)
        j = features.index(feature2)
        feat1_dist_prob[j] = pij
        # ant_route.append(i)
    
        print(f'{features.index(feature1)}' + f'--{features.index(feature2)}--' + f'{pij}')
    
        # feat1_dist_prob.append(dist_prob)
    ant_next_target_index = [key for key, value in feat1_dist_prob.items() if value == max(feat1_dist_prob.values())][0]
    traversed_nodes[i][j] = 1
    # mitting criterion
    ant_route.append(ant_next_target_index)
    fg_index = [key for key,value in feat1_dist_prob.items()]
    return ant_route, fg, traversed_nodes,fg_index,feat1_dist_prob,pheromone

In [60]:
a = [99,22]
a[-1]

22

In [61]:
ant_route = []
feature_s = ns.columns.tolist()
feature1 = feature_s[0]
feature_choices = features
pheromone = np.ones((ns.shape[1], ns.shape[1]))
traversed_nodes = np.zeros((ns.shape[1],ns.shape[1]))

while len(ant_route) < 10:
    ant_route, _, traversed_nodes, _, _, pheromone = next_ant_target(ant_route, feature1, feature_choices, pheromone, ns, traversed_nodes)
    print(f'antroute3 -- {ant_route}')
    feature1_index = ant_route[-1]
    feature1 = feature_s[feature1_index]
print(f'antroute4 -- {ant_route}')

antroute1 -- [0]
0--1--0.001401455262310136
0--2--0.0
0--3--0.0
0--4--0.0
0--5--0.0005506991428479221
0--6--0.0022439832552795247
0--7--0.004016667769287638
0--8--0.0
0--9--0.007100178049008313
0--10--0.0
0--11--0.0
0--12--0.0
0--13--0.0
0--14--0.0019475945497387437
0--15--0.003970892173563391
0--16--0.0024176981408798523
0--17--0.0
0--18--0.002347479880717203
0--19--0.0
0--20--0.0
0--21--0.010176304809302022
0--22--0.0009847219318264294
0--23--0.002131013006868446
0--24--0.0
0--25--0.0
0--26--0.0
0--27--0.001084775290018463
0--28--0.0
0--29--0.0028109388829424603
0--30--0.0
0--31--0.0024755991887082675
0--32--0.004208224063542534
0--33--0.007092101339538208
0--34--0.0
0--35--0.0014214334905631688
0--36--0.0031941196673904277
antroute3 -- [0, 21]
antroute1 -- [0, 21, 21]
antroute2 -- [0, 21]


ValueError: list.remove(x): x not in list

In [104]:
# mutual information differ every time we run it !!
features = ns.columns.tolist()
ant_route, fg, traversed_nodes,fg_index,feat1_dist_prob,pheromone = next_ant_target(features[0], features, pheromone, ns, traversed_nodes=traversed_nodes)
# ant_rout[-1] = feature1
# fg = features
# traversed_nodes = traversed_nodes
# pheromone = pheromone
print('pheromone' + f'{pheromone}')
print('ant_route' + f'{ant_route}')
print('fg' + f'{fg}')
print('traversed_nodes' + f'{traversed_nodes}')
print('fg_index' + f'{fg_index}')
print('feat1_dist_prob' + f'{feat1_dist_prob}')

TypeError: next_ant_target() missing 1 required positional argument: 'ant_route'

In [109]:
features = ns.columns.tolist()
features

['bkblk_t',
 'bknwy_t',
 'bkon8_t',
 'bkona_t',
 'bkspr_t',
 'bkxbq_t',
 'bkxcr_t',
 'bkxwp_t',
 'blxwp_t',
 'bxqsq_t',
 'cntxt_t',
 'dsopp_t',
 'dwipd_l',
 'hdchk_t',
 'katri_n',
 'katri_w',
 'mulch_t',
 'qxmsq_t',
 'r2ar8_t',
 'reskd_t',
 'reskr_t',
 'rimmx_t',
 'rkxwp_t',
 'rxmsq_t',
 'simpl_t',
 'skach_t',
 'skewr_t',
 'skrxp_t',
 'spcop_t',
 'stlmt_t',
 'thrsk_t',
 'wkcti_t',
 'wkna8_t',
 'wknck_t',
 'wkovl_t',
 'wkpos_t',
 'wtoeg_t']

In [118]:
pheromone = np.ones((ns.shape[1], ns.shape[1]))
traversed_nodes = np.zeros((ns.shape[1],ns.shape[1]))
base_features = ns.columns.tolist()
features = ns.columns.tolist()
feature1 = features[0]
ant_routes = []
while len(ant_route) < 10:
    ant_choice, fg, traversed_nodes_init,fg_index,feat1_dist_prob,pheromone_init = next_ant_target(feature1, features, pheromone, ns, traversed_nodes)
    feature1 = base_features[ant_choice[-1]]
    ant_routes.append(ant_choice[0])
    # features = fg
    # traversed_nodes = traversed_nodes_init
    # pheromone = pheromone_init
    # ant_route = ant_route_init
print('pheromone' + f'{pheromone}')
print('ant_route' + f'{ant_routes}')
print('fg' + f'{fg}')
print('traversed_nodes' + f'{traversed_nodes}')
print('fg_index' + f'{fg_index}')
print('feat1_dist_prob' + f'{feat1_dist_prob}')

pheromone[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
ant_route[]
fg['bknwy_t', 'bkon8_t', 'bkona_t', 'bkspr_t', 'bkxbq_t', 'bkxcr_t', 'bkxwp_t', 'blxwp_t', 'bxqsq_t', 'cntxt_t', 'dsopp_t', 'dwipd_l', 'hdchk_t', 'katri_n', 'katri_w', 'mulch_t', 'qxmsq_t', 'r2ar8_t', 'reskd_t', 'reskr_t', 'rimmx_t', 'rkxwp_t', 'rxmsq_t', 'simpl_t', 'skach_t', 'skewr_t', 'skrxp_t', 'spcop_t', 'stlmt_t', 'thrsk_t', 'wkcti_t', 'wkna8_t', 'wknck_t', 'wkovl_t', 'wkpos_t', 'wtoeg_t']
traversed_nodes[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
fg_index[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
feat1_dist_prob{1: 0.001401455262310136, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0005506991428479221, 6: 0.0022439832552

In [52]:
features = ns.columns.tolist()
alpha = 0.5
beta = 0.5
pijk = probability_transition_rule(features[0], features[3], pheromone, alpha, beta)
pijk

0.00043925640287619693

An ANT COLONY from Bing Chat GPT

In [1]:
import numpy as np
import pandas as pd

def ant_colony_algorithm(feature_matrix, landa):
    # initialize pheromone matrix
    pheromone = np.ones(feature_matrix.shape[1])
    # initialize ant colony
    ants = np.zeros((feature_matrix.shape[0], feature_matrix.shape[1]))
    # initialize best feature subset
    best_subset = []
    # initialize best score
    best_score = 0
    
    # iterate until stopping criterion is met
    while True:
        # iterate over each ant
        for i in range(ants.shape[0]):
            # calculate probability of selecting each feature
            probability = pheromone / np.sum(pheromone)
            # select features based on probability
            selected_features = np.random.choice(feature_matrix.shape[1], size=10000, replace=False, p=probability)
            # add selected features to ant colony
            ants[i, selected_features] = 1
        
        # calculate score for each feature subset
        scores = np.sum(ants * feature_matrix, axis=1) / np.sum(feature_matrix, axis=1)
        # find best feature subset and score
        best_subset = ants[np.argmax(scores)]
        best_score = np.max(scores)
        
        # update pheromone matrix based on best feature subset
        pheromone *= (1 - landa)
        pheromone += landa * best_subset
        
        # check stopping criterion
        if best_score >= landa:
            break
    
    return best_subset

# example usage
feature_matrix = pd.DataFrame(np.random.rand(1000, 10000))
landa = 0.5

best_subset = ant_colony_algorithm(feature_matrix, landa)

print(best_subset)

[1. 1. 1. ... 1. 1. 1.]


AUROC: 0.9989316239316239
accuracy: 0.9736842105263158


TypeError: 'AdaBoostClassifier' object is not callable